language: swift
osx_image: xcode8.3
branches:
  only:
    - master
script:
  - if [ $MODE == 'Tests' ]; then xcodebuild -workspace gattaca.xcworkspace -scheme gattaca -sdk "iphonesimulator" -destination "platform=iOS Simulator,OS=10.0,name=iPhone 6s" -enableCodeCoverage YES clean build test | xcpretty; fi
  - if [ $MODE == 'Build' ]; then xcodebuild -workspace gattaca.xcworkspace -scheme gattaca -sdk "iphonesimulator" -destination "platform=iOS Simulator,OS=10.0,name=iPhone 6s" clean build | xcpretty; fi
after_script:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - MODE=Tests
  - MODE=Build
